name: Node CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 22.x
        uses: actions/setup-node@v7
        with:
          node-version: 22.x
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install --immutable
          yarn build
        env:
          CI: true
      - name: Run typecheck and linter
        run: |
          yarn lint
        env:
          CI: true

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install --immutable
        env:
          CI: true
      - name: Run tests
        run: |
          yarn unit --coverage=true
        env:
          CI: true
      - name: Send coverage
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.node-version == '22.x'
      - name: Check docs generation
        if: matrix.node-version == '22.x'
        run: |
          yarn docs
        env:
          CI: true

  validate-dependencies:
    name: Validate production dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 22.x
        uses: actions/setup-node@v7
        with:
          node-version: 22.x
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install --immutable
        env:
          CI: true
      - name: Validate production dependencies
        run: |
          if ! git log --format=oneline -n 1 | grep -q "\[ignore-audit\]"; then
            yarn validate:dependencies
          else
            echo "Skipping audit"
          fi
        env:
          CI: true
  validate-all-dependencies:
    name: Validate all dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 22.x
        uses: actions/setup-node@v7
        with:
          node-version: 22.x
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install --immutable
        env:
          CI: true
      - name: Validate production dependencies
        run: |
          yarn validate:dependencies
        env:
          CI: true
      - name: Validate dev dependencies
        run: |
          yarn validate:dev-dependencies
        env:
          CI: true
